# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Product' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Product
  pod 'SwiftLint'

  target 'ProductTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ProductUITests' do
    # Pods for testing
  end

end
